import Link from "next/link";

export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

function About() {
  return (
    <div>
      <h1>About</h1>
      <div>
        <Link href={"/"}>Home</Link>
      </div>
    </div>
  );
}

export default About;
