import Link from "next/link";

export const metadata = {
  title: "About Team Page",
  description: "Generated by create next app",
};

function AboutTeam() {
  return (
    <div>
      <h1>AboutTeam</h1>
      <Link href={"/"}>Home</Link>
      <div></div>
    </div>
  );
}

export default AboutTeam;
